const fs = require('fs');
const PDFDocument = require('pdfkit');
const path = require('path');

const outputDir = path.join(__dirname, 'mock_data');
if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir);
}

// --- CSV Generators ---
const salesCsvContent = `Invoice_ID,Contract_Date,Customer_Name,Region,Product_Tier,ARR_USD,Contract_Term_Months,Renewal_Risk
INV-9901,2023-03-01,Northwind Retail LLC,NAMER,Enterprise,1200000,36,High
INV-9902,2024-01-15,Oceanic Airlines,APAC,Professional,450000,12,Low
INV-9903,2024-06-10,Globex Corporation,EMEA,Enterprise,950000,24,Medium
INV-9904,2022-11-01,Initech,NAMER,Professional,320000,12,Low
INV-9905,2025-01-20,Umbrella Corp,EMEA,Enterprise,1500000,36,Medium`;

const orgCsvContent = `Emp_ID,First_Name,Last_Name,Title,Department,Manager_ID,Location,Base_Salary,Stock_Unvested
1001,Elena,Rostova,CEO,Executive,NULL,New York,450000,500000
1002,Aris,Thorne,CTO,Engineering,1001,San Francisco,320000,150000
1003,Marcus,Vance,VP Sales,Sales,1001,Chicago,250000,80000
1004,Sarah,Jenkins,Lead Architect,Engineering,1002,Remote-US,210000,45000
1005,David,Chen,Data Scientist,Engineering,1004,Remote-US,185000,20000
1006,Maria,Gonzalez,General Counsel,Legal,1001,New York,290000,90000`;

fs.writeFileSync(path.join(outputDir, 'sales_pipeline_export.csv'), salesCsvContent);
fs.writeFileSync(path.join(outputDir, 'org_census_q1.csv'), orgCsvContent);

// --- PDF Generator Helper ---
function createPDF(filename, title, content) {
    const doc = new PDFDocument({ margin: 50 });
    const writeStream = fs.createWriteStream(path.join(outputDir, filename));
    doc.pipe(writeStream);
    
    doc.fontSize(16).font('Helvetica-Bold').text(title, { align: 'center' });
    doc.moveDown();
    doc.fontSize(11).font('Helvetica').text(content, { align: 'left', lineGap: 4 });
    
    doc.end();
}

// --- PDF Content ---
const ctoContract = `THIS EMPLOYMENT AGREEMENT (the "Agreement") is made and entered into as of January 15, 2022, by and between Nova Analytics, a Delaware Corporation (the "Company"), and Dr. Aris Thorne (the "Executive").

1. POSITION AND DUTIES
The Company hereby employs the Executive as Chief Technology Officer (CTO).

2. COMPENSATION
2.1 Base Salary: $320,000 per year.
2.2 Bonus: Up to 40% of the Base Salary.

3. EQUITY GRANTS
150,000 Restricted Stock Units (RSUs) subject to a 4-year vesting schedule.

4. CHANGE OF CONTROL (SPECIAL PROVISION)
4.1 In the event of a "Change of Control" (acquisition of >50% voting stock), 100% of the Executive's unvested RSUs shall immediately accelerate and vest.
4.2 If terminated within 12 months following a Change of Control, the Executive shall receive a lump sum equal to 24 months of Base Salary plus target bonus.`;

const customerMsa = `This MSA is effective as of March 1, 2023, between Nova Analytics ("Provider") and Northwind Retail LLC ("Customer").

1. SERVICES PROVIDED
Access to the Nova Data Processing Platform.

2. EXCLUSIVITY
Customer shall use Provider as its exclusive vendor. Provider agrees not to license the Platform to Direct Competitors of the Customer in the North American market.

3. DATA RESIDENCY AND SECURITY
All Customer Data generated by EU-based subsidiaries must be processed and stored exclusively in servers located within the European Union (Frankfurt region). No EU data shall be routed or backed up to US-based servers.

4. CHANGE OF CONTROL
If Provider undergoes a Change of Control, Customer reserves the right to terminate this Agreement immediately without penalty and receive a pro-rated refund.`;

const infoSecPolicy = `1. OVERVIEW
Standard operating procedures for IT infrastructure at Nova Analytics.

2. CLOUD INFRASTRUCTURE
Nova Analytics operates primarily on Amazon Web Services (AWS). Production databases are hosted in US-East-1 (N. Virginia) and EU-Central-1 (Frankfurt).

3. DISASTER RECOVERY & BACKUPS
Standard Procedure: All EU-Central-1 databases have an asynchronous failover backup routed to US-East-1 daily at 00:00 UTC. This applies to all tenants unless specifically air-gapped by manual engineering overrides.

4. OPEN SOURCE SOFTWARE (OSS) POLICY
Use of GPL v3 or AGPL licensed software is strictly prohibited.`;

// --- Generate PDFs ---
createPDF('employee_contract_CTO.pdf', 'EMPLOYMENT AGREEMENT', ctoContract);
createPDF('customer_msa_northwind.pdf', 'MASTER SUBSCRIPTION AGREEMENT', customerMsa);
createPDF('infosec_policy.pdf', 'NOVA ANALYTICS - INTERNAL IT & INFOSEC POLICY', infoSecPolicy);

console.log('✅ Successfully generated all 5 M&A documents in the /mock_data folder!');